### ISSUE TITLE
SRTM1_DIR and SRTM3_DIR as local variables instead of ENV variables

### ISSUE THREAD

**Issue by ugnelis** [adamcharnock/python-srtm#2]
If I have a few sources of `.hgt` datasets, and I want to switch depending on the use case, it would be neat to call  `Srtm1HeightMapCollection()` lib like this:

```python
from srtm import Srtm3HeightMapCollection
srtm3_data = Srtm3HeightMapCollection('/path/to/srtm3/')
```

instead of defining environment variables.

By the way, very nice lib, it saved some time for me :)

**Comment by adamcharnock** [comment]
Hi @ugnelis! Thank you for the issue, and sorry it has taken ages to get back to you. I think this is already possible:

```
from pathlib import Path
from srtm import Srtm3HeightMapCollection

srtm3_data = Srtm3HeightMapCollection(hgt_dir=Path('/path/to/srtm3/'))
```

And I'm glad the library is useful!
