### ISSUE TITLE
Does it do interpolation when higher precision inputs are provided?

### ISSUE THREAD

**Issue by quan787** [adamcharnock/python-srtm#4]
I only have 90-m resolution datasets, but I need the output to be smooth because optimization sometimes doesn't converge.
So would you add the feature that do interpolations of any sort when specified?

**Comment by adamcharnock** [comment]
Hi @quan787, as I am sure you have gathered by now, my focus hasn't been on this project for a while so I am not in a place to add new features. Always open to sensible PRs though.
