### ISSUE TITLE
Issue for places below sea level

### ISSUE THREAD

**Issue by quan787** [adamcharnock/python-srtm#5]
For the srtm datasets, elevations of places below sea level (e.g. dead sea) are slightly smaller than 65535, which means (obviously) they are 65535 based. 
So would you add the feature that automatically output negative values? Or is it prefered to provide only the raw data?

**Comment by yehudarav** [comment]
Its an easy fix. 

Line 76 in heights_maps.py is
`        return int.from_bytes(
            self.raster[byte_number : byte_number + 2], byteorder="big"
        )
`
but should be 
`        return int.from_bytes(
            self.raster[byte_number : byte_number + 2], byteorder="big",signed=True
        )
`

I fixed it, but I don't have permissions.
@adamcharnock Can you please add me

**Comment by ahemwe** [comment]
@adamcharnock Could you please consider this proposal so that a fix is available in pip?

**Comment by adamcharnock** [comment]
Done! Version 0.6 now in PyPi 🎉
